### PR TITLE
C api add posit256

### PR DESCRIPTION
**Pull request by cjdelisle**
I noticed you added a test for posit256 type, this adds posit256 and makes the test build properly. It should be a good reference for adding types in the future since it shows what needs to be changed in the macro rat's nest.

### CODE REVIEW

**Comment by cjdelisle** [comment]
Oops, looks like we stepped on eachothers' toes.
Make sure you pull the change I made in posit_c_macros.h and everything should be fine. Also be sure that you're using posit_equals() correctly, it looks like an inverted if (`posit_equals() == true` if `posit_cmp() == 0`)

**Comment by Ravenwater** [comment]
yep, working on the same code makes that high probability. Let me take a look how easy the merge is to get synced up again.

**Comment by cjdelisle** [comment]
You can discard all of my code except for what I commented on. But you might want to make sure you're using the generic code in order to verify that the generics are ok.  In the future we might consider just implementing a big .h file with all the tests in it and including it in each .c file the same way as _macros.h is done. Also maybe switch to testing with mpfr ?

**Comment by Ravenwater** [comment]
posit8 is now failing, and posit128 is weirdly slow compared to the others....
```
Test project /home/stillwater/dev/clones/universal/build
    Start 1: areal_16dot5_float
1/9 Test #1: areal_16dot5_float ...............   Passed    0.00 sec
    Start 2: areal_8dot2_float
2/9 Test #2: areal_8dot2_float ................   Passed    0.00 sec
    Start 3: areal_arithmetic_add
3/9 Test #3: areal_arithmetic_add .............   Passed    0.00 sec
    Start 4: c_api_posit128
4/9 Test #4: c_api_posit128 ...................   Passed   13.19 sec
    Start 5: c_api_posit16
5/9 Test #5: c_api_posit16 ....................   Passed    0.15 sec
    Start 6: c_api_posit256
6/9 Test #6: c_api_posit256 ...................   Passed    0.97 sec
    Start 7: c_api_posit32
7/9 Test #7: c_api_posit32 ....................   Passed    0.06 sec
    Start 8: c_api_posit64
8/9 Test #8: c_api_posit64 ....................   Passed    0.35 sec
    Start 9: c_api_posit8
9/9 Test #9: c_api_posit8 .....................***Failed    0.28 sec

89% tests passed, 1 tests failed out of 9

Total Test time (real) =  15.40 sec

The following tests FAILED:
          9 - c_api_posit8 (Failed)
Errors while running CTest
```

**Pull request merged**
