### PR TITLE
added a .cpp to do runge - kutta using posits.

### PR DESCRIPTION
**Pull request by jtodd440**
I was trying to use pi/4 as the interval size /  step size
to show the difference in precision but I was having trouble with that.
Take a look and let me know what you think :)

### CODE REVIEW

**Review by Ravenwater — COMMENTED** [review]
The DS_Store files need to be removed. Best way to do that is to add them to the .gitignore file in the root of the project

**Review by Ravenwater — COMMENTED** [review]
You should do this type of development in a feature branch. Before you do anything in a repo, figure out what you want to do and then create a branch for that with:

> git checkout -b my-branch-name

from that point on all your edits will be tracked in the branch, and you will still have the option to go back to the main line by executing this command:

> git checkout master

we'll continue this PR in your master branch, but future efforts should come in their own branch.

**Review by Ravenwater — CHANGES_REQUESTED** [review]
M_PI and its derivatives are not part of the C++ standard:

You need to add the #define _USE_MATH_DEFINES and #include <cmath> as shown.

**Comment by Ravenwater** [comment]
Jake: do you get the notifications when I add a review note? Wondering what
you see on your end.

   *Dr. E. Theodore L. Omtzigt*

CEO and Founder

Stillwater Supercomputing, Inc.



East Coast Office : (617) 314 6424

West Coast Office: (415) 738 7387

Mobile phone #  : (916) 296-7901

95 South Freeport Road, #720
South Freeport, ME 04078-0720

**Comment by jtodd440** [comment]
Yes, I am getting the notifications via email of the changes. I can see
them on GitHub as well.

**Comment by Ravenwater** [comment]
Jake: if you remove the DS files from this PR, I can merge this

**Comment by jtodd440** [comment]
How do I add that to the .gitignore? Is that a file that already exists or
do I need to create it?

**Comment by Ravenwater** [comment]
It already exists and is in the root:
https://github.com/stillwater-sc/universal/blob/master/.gitignore

all you will need is to add a comment describing which application generates the .DS_store file and then add it as a file pattern to ignore. When you do that, git commands will filter these files out so they don't end up in a PR.

**Comment by jtodd440** [comment]
I was having some trouble for a moment but I think it’s resolved now. Did
you get my changes?

**Comment by Ravenwater** [comment]
don't quite understand why the .DS_Store file under applications didn't disappear, but I can fix that after the merge.

I'll merge this

**Comment by jtodd440** [comment]
Nevermind, I figured it out. I will submit it again shortly.

**Comment by Ravenwater** [comment]
Hi Jacob:

I already merged your PR, so you should not have to do anything further

   *Dr. E. Theodore L. Omtzigt*

CEO and Founder

Stillwater Supercomputing, Inc.



East Coast Office : (617) 314 6424

West Coast Office: (415) 738 7387

Mobile phone #  : (916) 296-7901

95 South Freeport Road, #720
South Freeport, ME 04078-0720

**Pull request merged**
